server:
  port: 8800
logging:
  path: logs
  file: userManger.log
spring:
  application:
    name: userManager
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.94.151.50:3306/course?serverTimeZone=GMT
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*
